players:
  - name: Bob
    ships:
      - type: carrier
        start: A1
        orientation: horizontal

  - name: Joe
    ships:
      - type: carrier
        start: D3
        orientation: vertical
